// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Du Map
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.10
 */

package openapi

import (
	"context"
	"net/http"
)



// MapAPIRouter defines the required methods for binding the api requests to a responses for the MapAPI
// The MapAPIRouter implementation should parse necessary information from the http request,
// pass the data to a MapAPIServicer to perform the required actions, then write the service results to the http response.
type MapAPIRouter interface { 
	GetFaces(http.ResponseWriter, *http.Request)
	UpdateTile(http.ResponseWriter, *http.Request)
}
// ScanAPIRouter defines the required methods for binding the api requests to a responses for the ScanAPI
// The ScanAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ScanAPIServicer to perform the required actions, then write the service results to the http response.
type ScanAPIRouter interface { 
	SaveScan(http.ResponseWriter, *http.Request)
}
// SharesAPIRouter defines the required methods for binding the api requests to a responses for the SharesAPI
// The SharesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a SharesAPIServicer to perform the required actions, then write the service results to the http response.
type SharesAPIRouter interface { 
	ChangeShare(http.ResponseWriter, *http.Request)
	GetShares(http.ResponseWriter, *http.Request)
}


// MapAPIServicer defines the api actions for the MapAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type MapAPIServicer interface { 
	GetFaces(context.Context, int64, int64, int64) (ImplResponse, error)
	UpdateTile(context.Context, string, int64) (ImplResponse, error)
}


// ScanAPIServicer defines the api actions for the ScanAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ScanAPIServicer interface { 
	SaveScan(context.Context, Scan) (ImplResponse, error)
}


// SharesAPIServicer defines the api actions for the SharesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SharesAPIServicer interface { 
	ChangeShare(context.Context, string, float32, string) (ImplResponse, error)
	GetShares(context.Context) (ImplResponse, error)
}
