// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Du Map
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.10
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// SharesAPIService is a service that implements the logic for the SharesAPIServicer
// This service should implement the business logic for every endpoint for the SharesAPI API.
// Include any external packages or services that will be required by this service.
type SharesAPIService struct {
}

// NewSharesAPIService creates a default api service
func NewSharesAPIService() *SharesAPIService {
	return &SharesAPIService{}
}

// ChangeShare - 
func (s *SharesAPIService) ChangeShare(ctx context.Context, category string, shareId float32, action string) (ImplResponse, error) {
	// TODO - update ChangeShare with the required logic for this service method.
	// Add api_shares_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ChangeShare method not implemented")
}

// GetShares - 
func (s *SharesAPIService) GetShares(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetShares with the required logic for this service method.
	// Add api_shares_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Share{}) or use other options such as http.Ok ...
	// return Response(200, []Share{}), nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetShares method not implemented")
}
