// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Du Map
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.10
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ScanAPIService is a service that implements the logic for the ScanAPIServicer
// This service should implement the business logic for every endpoint for the ScanAPI API.
// Include any external packages or services that will be required by this service.
type ScanAPIService struct {
}

// NewScanAPIService creates a default api service
func NewScanAPIService() *ScanAPIService {
	return &ScanAPIService{}
}

// SaveScan - 
func (s *ScanAPIService) SaveScan(ctx context.Context, body Scan) (ImplResponse, error) {
	// TODO - update SaveScan with the required logic for this service method.
	// Add api_scan_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SaveScan method not implemented")
}
