// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Du Map
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.10
 */

package openapi




type RgbColor struct {

	R float32 `json:"r"`

	G float32 `json:"g"`

	B float32 `json:"b"`
}

// AssertRgbColorRequired checks if the required fields are not zero-ed
func AssertRgbColorRequired(obj RgbColor) error {
	elements := map[string]interface{}{
		"r": obj.R,
		"g": obj.G,
		"b": obj.B,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRgbColorConstraints checks if the values respects the defined constraints
func AssertRgbColorConstraints(obj RgbColor) error {
	return nil
}
